Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%run -i ../python/common.py
%run -i ../python/ln_preamble.py
# Make three extra terminals to serve as example of 3 terminal emulators
# We do this to avoid having to change the dimensions of our standard
# Editor, Build and debugger terminals
try:
    EXTERM1=TERMINALS[3]['name']
except IndexError:
    EXTERM1=mkTerm()
try:
    EXTERM2=TERMINALS[4]['name']
except IndexError:
    EXTERM2=mkTerm()
try:
    EXTERM3=TERMINALS[5]['name']
except IndexError:
    EXTERM3=mkTerm()
try:
    HHTERM=TERMINALS[6]['name']
except IndexError:
    HHTERM=mkTerm()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/opt/app-root/src/UndertheCovers/underthecovers/python/ln_preamble.py[0m in [0;36m<module>[0;34m[0m
[1;32m      5[0m [0;31m# Editor, Build and debugger terminals[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 7[0;31m     [0mEXTERM1[0m[0;34m=[0m[0mTERMINALS[0m[0;34m[[0m[0;36m3[0m[0;34m][0m[0;34m[[0m[0;34m'name'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      8[0m [0;32mexcept[0m [0mIndexError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      9[0m     [0mEXTERM1[0m[0;34m=[0m[0mmkTerm[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'TERMINALS' is not defined
NameError: name 'TERMINALS' is not defined

